/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_FILE_SYSTEM_COMMANDS_PB_H_INCLUDED
#define PB_FILE_SYSTEM_COMMANDS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _DirItemType { 
    DirItemType_DIT_NOT_SET = 0, 
    DirItemType_DIT_FILE = 1, 
    DirItemType_DIT_DIR = 2 
} DirItemType;

/* Struct definitions */
typedef struct _DirItem { 
    char name[32]; 
    DirItemType dirItemType; 
    uint32_t filesize; 
} DirItem;

typedef struct _FileData { 
    char filename[32]; 
    uint32_t filesize; 
    uint32_t checksum; 
} FileData;

typedef struct _ListDirContentsCommand { 
    char dirPath[32]; 
} ListDirContentsCommand;

typedef struct _ListDirContentsResponse { 
    char dirPath[32]; 
    pb_callback_t dirItems; 
} ListDirContentsResponse;

typedef struct _PrintDirContentsCommand { 
    char dirPath[32]; 
} PrintDirContentsCommand;

typedef struct _PrintFileContentsCommand { 
    char filePath[32]; 
} PrintFileContentsCommand;

typedef struct _ReportFileDataCommand { 
    char filename[32]; 
} ReportFileDataCommand;

typedef struct _ResetFilesystemCommand { 
    bool dummy; 
} ResetFilesystemCommand;

typedef struct _ResetFilesystemResponse { 
    bool success; 
} ResetFilesystemResponse;

typedef struct _RmFileCommand { 
    char filePath[12]; 
} RmFileCommand;

typedef struct _ReportFileDataResponse { 
    bool fileExists; 
    bool has_fileData;
    FileData fileData; 
} ReportFileDataResponse;

typedef struct _RmFileResponse { 
    bool success; 
    bool has_rmDirCommand;
    RmFileCommand rmDirCommand; 
} RmFileResponse;

typedef struct _StoreUpcomingFileDataCommand { 
    bool has_fileData;
    FileData fileData; 
} StoreUpcomingFileDataCommand;

typedef struct _StoreUpcomingFileDataResponse { 
    bool success; 
    uint32_t bytesWritten; 
    bool has_command;
    FileData command; 
} StoreUpcomingFileDataResponse;

typedef struct _FileSystemCommand { 
    /* MkDirCommand mkDirCommand = 1; */
    pb_size_t which_command;
    union {
        PrintDirContentsCommand printDirContentsCommand;
        PrintFileContentsCommand printFileContentsCommand;
        RmFileCommand rmFileCommand;
        StoreUpcomingFileDataCommand storeUpcomingFileDataCommand;
        ReportFileDataCommand reportFileDataCommand;
        ListDirContentsCommand listDirContentsCommand;
        ResetFilesystemCommand resetFilesystemCommand;
    } command; 
} FileSystemCommand;

typedef struct _FileSystemResponse { 
    /* MkDirResponse mkDirCommand = 1; */
    pb_size_t which_response;
    union {
        RmFileResponse rmFileCommand;
        StoreUpcomingFileDataResponse storeUpcomingFileDataResponse;
        ReportFileDataResponse reportFileDataResponse;
        ListDirContentsResponse listDirContentsResponse;
        ResetFilesystemResponse resetFilesystemResponse;
    } response; 
} FileSystemResponse;


/* Helper constants for enums */
#define _DirItemType_MIN DirItemType_DIT_NOT_SET
#define _DirItemType_MAX DirItemType_DIT_DIR
#define _DirItemType_ARRAYSIZE ((DirItemType)(DirItemType_DIT_DIR+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define DirItem_init_default                     {"", _DirItemType_MIN, 0}
#define FileData_init_default                    {"", 0, 0}
#define StoreUpcomingFileDataCommand_init_default {false, FileData_init_default}
#define StoreUpcomingFileDataResponse_init_default {0, 0, false, FileData_init_default}
#define RmFileCommand_init_default               {""}
#define RmFileResponse_init_default              {0, false, RmFileCommand_init_default}
#define ReportFileDataCommand_init_default       {""}
#define ReportFileDataResponse_init_default      {0, false, FileData_init_default}
#define ListDirContentsCommand_init_default      {""}
#define ListDirContentsResponse_init_default     {"", {{NULL}, NULL}}
#define PrintDirContentsCommand_init_default     {""}
#define ResetFilesystemCommand_init_default      {0}
#define ResetFilesystemResponse_init_default     {0}
#define PrintFileContentsCommand_init_default    {""}
#define FileSystemCommand_init_default           {0, {PrintDirContentsCommand_init_default}}
#define FileSystemResponse_init_default          {0, {RmFileResponse_init_default}}
#define DirItem_init_zero                        {"", _DirItemType_MIN, 0}
#define FileData_init_zero                       {"", 0, 0}
#define StoreUpcomingFileDataCommand_init_zero   {false, FileData_init_zero}
#define StoreUpcomingFileDataResponse_init_zero  {0, 0, false, FileData_init_zero}
#define RmFileCommand_init_zero                  {""}
#define RmFileResponse_init_zero                 {0, false, RmFileCommand_init_zero}
#define ReportFileDataCommand_init_zero          {""}
#define ReportFileDataResponse_init_zero         {0, false, FileData_init_zero}
#define ListDirContentsCommand_init_zero         {""}
#define ListDirContentsResponse_init_zero        {"", {{NULL}, NULL}}
#define PrintDirContentsCommand_init_zero        {""}
#define ResetFilesystemCommand_init_zero         {0}
#define ResetFilesystemResponse_init_zero        {0}
#define PrintFileContentsCommand_init_zero       {""}
#define FileSystemCommand_init_zero              {0, {PrintDirContentsCommand_init_zero}}
#define FileSystemResponse_init_zero             {0, {RmFileResponse_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define DirItem_name_tag                         1
#define DirItem_dirItemType_tag                  2
#define DirItem_filesize_tag                     3
#define FileData_filename_tag                    1
#define FileData_filesize_tag                    2
#define FileData_checksum_tag                    3
#define ListDirContentsCommand_dirPath_tag       1
#define ListDirContentsResponse_dirPath_tag      1
#define ListDirContentsResponse_dirItems_tag     2
#define PrintDirContentsCommand_dirPath_tag      1
#define PrintFileContentsCommand_filePath_tag    1
#define ReportFileDataCommand_filename_tag       1
#define ResetFilesystemCommand_dummy_tag         1
#define ResetFilesystemResponse_success_tag      1
#define RmFileCommand_filePath_tag               1
#define ReportFileDataResponse_fileExists_tag    1
#define ReportFileDataResponse_fileData_tag      2
#define RmFileResponse_success_tag               1
#define RmFileResponse_rmDirCommand_tag          2
#define StoreUpcomingFileDataCommand_fileData_tag 1
#define StoreUpcomingFileDataResponse_success_tag 1
#define StoreUpcomingFileDataResponse_bytesWritten_tag 2
#define StoreUpcomingFileDataResponse_command_tag 3
#define FileSystemCommand_printDirContentsCommand_tag 1
#define FileSystemCommand_printFileContentsCommand_tag 2
#define FileSystemCommand_rmFileCommand_tag      3
#define FileSystemCommand_storeUpcomingFileDataCommand_tag 6
#define FileSystemCommand_reportFileDataCommand_tag 7
#define FileSystemCommand_listDirContentsCommand_tag 8
#define FileSystemCommand_resetFilesystemCommand_tag 9
#define FileSystemResponse_rmFileCommand_tag     2
#define FileSystemResponse_storeUpcomingFileDataResponse_tag 6
#define FileSystemResponse_reportFileDataResponse_tag 7
#define FileSystemResponse_listDirContentsResponse_tag 8
#define FileSystemResponse_resetFilesystemResponse_tag 9

/* Struct field encoding specification for nanopb */
#define DirItem_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, UENUM,    dirItemType,       2) \
X(a, STATIC,   SINGULAR, UINT32,   filesize,          3)
#define DirItem_CALLBACK NULL
#define DirItem_DEFAULT NULL

#define FileData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   filename,          1) \
X(a, STATIC,   SINGULAR, UINT32,   filesize,          2) \
X(a, STATIC,   SINGULAR, UINT32,   checksum,          3)
#define FileData_CALLBACK NULL
#define FileData_DEFAULT NULL

#define StoreUpcomingFileDataCommand_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  fileData,          1)
#define StoreUpcomingFileDataCommand_CALLBACK NULL
#define StoreUpcomingFileDataCommand_DEFAULT NULL
#define StoreUpcomingFileDataCommand_fileData_MSGTYPE FileData

#define StoreUpcomingFileDataResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, STATIC,   SINGULAR, UINT32,   bytesWritten,      2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  command,           3)
#define StoreUpcomingFileDataResponse_CALLBACK NULL
#define StoreUpcomingFileDataResponse_DEFAULT NULL
#define StoreUpcomingFileDataResponse_command_MSGTYPE FileData

#define RmFileCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   filePath,          1)
#define RmFileCommand_CALLBACK NULL
#define RmFileCommand_DEFAULT NULL

#define RmFileResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  rmDirCommand,      2)
#define RmFileResponse_CALLBACK NULL
#define RmFileResponse_DEFAULT NULL
#define RmFileResponse_rmDirCommand_MSGTYPE RmFileCommand

#define ReportFileDataCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   filename,          1)
#define ReportFileDataCommand_CALLBACK NULL
#define ReportFileDataCommand_DEFAULT NULL

#define ReportFileDataResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     fileExists,        1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  fileData,          2)
#define ReportFileDataResponse_CALLBACK NULL
#define ReportFileDataResponse_DEFAULT NULL
#define ReportFileDataResponse_fileData_MSGTYPE FileData

#define ListDirContentsCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   dirPath,           1)
#define ListDirContentsCommand_CALLBACK NULL
#define ListDirContentsCommand_DEFAULT NULL

#define ListDirContentsResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   dirPath,           1) \
X(a, CALLBACK, REPEATED, MESSAGE,  dirItems,          2)
#define ListDirContentsResponse_CALLBACK pb_default_field_callback
#define ListDirContentsResponse_DEFAULT NULL
#define ListDirContentsResponse_dirItems_MSGTYPE DirItem

#define PrintDirContentsCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   dirPath,           1)
#define PrintDirContentsCommand_CALLBACK NULL
#define PrintDirContentsCommand_DEFAULT NULL

#define ResetFilesystemCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     dummy,             1)
#define ResetFilesystemCommand_CALLBACK NULL
#define ResetFilesystemCommand_DEFAULT NULL

#define ResetFilesystemResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1)
#define ResetFilesystemResponse_CALLBACK NULL
#define ResetFilesystemResponse_DEFAULT NULL

#define PrintFileContentsCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   filePath,          1)
#define PrintFileContentsCommand_CALLBACK NULL
#define PrintFileContentsCommand_DEFAULT NULL

#define FileSystemCommand_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,printDirContentsCommand,command.printDirContentsCommand),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,printFileContentsCommand,command.printFileContentsCommand),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,rmFileCommand,command.rmFileCommand),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,storeUpcomingFileDataCommand,command.storeUpcomingFileDataCommand),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,reportFileDataCommand,command.reportFileDataCommand),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,listDirContentsCommand,command.listDirContentsCommand),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,resetFilesystemCommand,command.resetFilesystemCommand),   9)
#define FileSystemCommand_CALLBACK NULL
#define FileSystemCommand_DEFAULT NULL
#define FileSystemCommand_command_printDirContentsCommand_MSGTYPE PrintDirContentsCommand
#define FileSystemCommand_command_printFileContentsCommand_MSGTYPE PrintFileContentsCommand
#define FileSystemCommand_command_rmFileCommand_MSGTYPE RmFileCommand
#define FileSystemCommand_command_storeUpcomingFileDataCommand_MSGTYPE StoreUpcomingFileDataCommand
#define FileSystemCommand_command_reportFileDataCommand_MSGTYPE ReportFileDataCommand
#define FileSystemCommand_command_listDirContentsCommand_MSGTYPE ListDirContentsCommand
#define FileSystemCommand_command_resetFilesystemCommand_MSGTYPE ResetFilesystemCommand

#define FileSystemResponse_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,rmFileCommand,response.rmFileCommand),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,storeUpcomingFileDataResponse,response.storeUpcomingFileDataResponse),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,reportFileDataResponse,response.reportFileDataResponse),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,listDirContentsResponse,response.listDirContentsResponse),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,resetFilesystemResponse,response.resetFilesystemResponse),   9)
#define FileSystemResponse_CALLBACK NULL
#define FileSystemResponse_DEFAULT NULL
#define FileSystemResponse_response_rmFileCommand_MSGTYPE RmFileResponse
#define FileSystemResponse_response_storeUpcomingFileDataResponse_MSGTYPE StoreUpcomingFileDataResponse
#define FileSystemResponse_response_reportFileDataResponse_MSGTYPE ReportFileDataResponse
#define FileSystemResponse_response_listDirContentsResponse_MSGTYPE ListDirContentsResponse
#define FileSystemResponse_response_resetFilesystemResponse_MSGTYPE ResetFilesystemResponse

extern const pb_msgdesc_t DirItem_msg;
extern const pb_msgdesc_t FileData_msg;
extern const pb_msgdesc_t StoreUpcomingFileDataCommand_msg;
extern const pb_msgdesc_t StoreUpcomingFileDataResponse_msg;
extern const pb_msgdesc_t RmFileCommand_msg;
extern const pb_msgdesc_t RmFileResponse_msg;
extern const pb_msgdesc_t ReportFileDataCommand_msg;
extern const pb_msgdesc_t ReportFileDataResponse_msg;
extern const pb_msgdesc_t ListDirContentsCommand_msg;
extern const pb_msgdesc_t ListDirContentsResponse_msg;
extern const pb_msgdesc_t PrintDirContentsCommand_msg;
extern const pb_msgdesc_t ResetFilesystemCommand_msg;
extern const pb_msgdesc_t ResetFilesystemResponse_msg;
extern const pb_msgdesc_t PrintFileContentsCommand_msg;
extern const pb_msgdesc_t FileSystemCommand_msg;
extern const pb_msgdesc_t FileSystemResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define DirItem_fields &DirItem_msg
#define FileData_fields &FileData_msg
#define StoreUpcomingFileDataCommand_fields &StoreUpcomingFileDataCommand_msg
#define StoreUpcomingFileDataResponse_fields &StoreUpcomingFileDataResponse_msg
#define RmFileCommand_fields &RmFileCommand_msg
#define RmFileResponse_fields &RmFileResponse_msg
#define ReportFileDataCommand_fields &ReportFileDataCommand_msg
#define ReportFileDataResponse_fields &ReportFileDataResponse_msg
#define ListDirContentsCommand_fields &ListDirContentsCommand_msg
#define ListDirContentsResponse_fields &ListDirContentsResponse_msg
#define PrintDirContentsCommand_fields &PrintDirContentsCommand_msg
#define ResetFilesystemCommand_fields &ResetFilesystemCommand_msg
#define ResetFilesystemResponse_fields &ResetFilesystemResponse_msg
#define PrintFileContentsCommand_fields &PrintFileContentsCommand_msg
#define FileSystemCommand_fields &FileSystemCommand_msg
#define FileSystemResponse_fields &FileSystemResponse_msg

/* Maximum encoded size of messages (where known) */
/* ListDirContentsResponse_size depends on runtime parameters */
/* FileSystemResponse_size depends on runtime parameters */
#define DirItem_size                             41
#define FileData_size                            45
#define FileSystemCommand_size                   49
#define ListDirContentsCommand_size              33
#define PrintDirContentsCommand_size             33
#define PrintFileContentsCommand_size            33
#define ReportFileDataCommand_size               33
#define ReportFileDataResponse_size              49
#define ResetFilesystemCommand_size              2
#define ResetFilesystemResponse_size             2
#define RmFileCommand_size                       13
#define RmFileResponse_size                      17
#define StoreUpcomingFileDataCommand_size        47
#define StoreUpcomingFileDataResponse_size       55

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
