/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_QROMA_POINT_CONFIG_PB_H_INCLUDED
#define PB_QROMA_POINT_CONFIG_PB_H_INCLUDED
#include <pb.h>
#include "qroma-types.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _QromaCommBtConfig { 
    uint32_t txIntervalInMs; 
    uint32_t maxTxMessageSizeInBytes; 
} QromaCommBtConfig;

typedef struct _QromaDeviceStatus { 
    Qroma_LogLevel logLevel; 
    Qroma_DebugCommMode debugCommMode; 
    uint32_t uptimeInMs; /* QromaDevicePowerStatus powerStatus = 4; */
} QromaDeviceStatus;

typedef struct _QromaDeviceVersion { 
    char softwareBuildVersion[100]; 
    char softwareCompileTime[30]; 
} QromaDeviceVersion;

typedef struct _QromaPointDetails { 
    char btQromaPointInstanceServiceUuid[37]; 
    char instanceId[9]; 
    char pointName[21]; 
    char driverId[21]; 
} QromaPointDetails;

typedef struct _QromaPointManifest { 
    char instanceId[11]; 
    char pointName[21]; 
    char driverId[21]; 
} QromaPointManifest;

typedef struct _QromaDeviceConfig { 
    bool has_qromaCommBtConfig;
    QromaCommBtConfig qromaCommBtConfig; /* QromaDevicePowerConfig powerConfig = 2; */
} QromaDeviceConfig;

typedef struct _QromaDeviceManifest { 
    char deviceName[30]; 
    uint32_t pointCount; 
    QromaPointDetails qromaPointDetails[5]; 
} QromaDeviceManifest;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define QromaPointDetails_init_default           {"", "", "", ""}
#define QromaPointManifest_init_default          {"", "", ""}
#define QromaDeviceManifest_init_default         {"", 0, {QromaPointDetails_init_default, QromaPointDetails_init_default, QromaPointDetails_init_default, QromaPointDetails_init_default, QromaPointDetails_init_default}}
#define QromaDeviceVersion_init_default          {"", ""}
#define QromaCommBtConfig_init_default           {0, 0}
#define QromaDeviceConfig_init_default           {false, QromaCommBtConfig_init_default}
#define QromaDeviceStatus_init_default           {_Qroma_LogLevel_MIN, _Qroma_DebugCommMode_MIN, 0}
#define QromaPointDetails_init_zero              {"", "", "", ""}
#define QromaPointManifest_init_zero             {"", "", ""}
#define QromaDeviceManifest_init_zero            {"", 0, {QromaPointDetails_init_zero, QromaPointDetails_init_zero, QromaPointDetails_init_zero, QromaPointDetails_init_zero, QromaPointDetails_init_zero}}
#define QromaDeviceVersion_init_zero             {"", ""}
#define QromaCommBtConfig_init_zero              {0, 0}
#define QromaDeviceConfig_init_zero              {false, QromaCommBtConfig_init_zero}
#define QromaDeviceStatus_init_zero              {_Qroma_LogLevel_MIN, _Qroma_DebugCommMode_MIN, 0}

/* Field tags (for use in manual encoding/decoding) */
#define QromaCommBtConfig_txIntervalInMs_tag     1
#define QromaCommBtConfig_maxTxMessageSizeInBytes_tag 2
#define QromaDeviceStatus_logLevel_tag           1
#define QromaDeviceStatus_debugCommMode_tag      2
#define QromaDeviceStatus_uptimeInMs_tag         3
#define QromaDeviceVersion_softwareBuildVersion_tag 1
#define QromaDeviceVersion_softwareCompileTime_tag 2
#define QromaPointDetails_btQromaPointInstanceServiceUuid_tag 1
#define QromaPointDetails_instanceId_tag         2
#define QromaPointDetails_pointName_tag          3
#define QromaPointDetails_driverId_tag           4
#define QromaPointManifest_instanceId_tag        1
#define QromaPointManifest_pointName_tag         2
#define QromaPointManifest_driverId_tag          3
#define QromaDeviceConfig_qromaCommBtConfig_tag  1
#define QromaDeviceManifest_deviceName_tag       1
#define QromaDeviceManifest_pointCount_tag       2
#define QromaDeviceManifest_qromaPointDetails_tag 3

/* Struct field encoding specification for nanopb */
#define QromaPointDetails_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   btQromaPointInstanceServiceUuid,   1) \
X(a, STATIC,   SINGULAR, STRING,   instanceId,        2) \
X(a, STATIC,   SINGULAR, STRING,   pointName,         3) \
X(a, STATIC,   SINGULAR, STRING,   driverId,          4)
#define QromaPointDetails_CALLBACK NULL
#define QromaPointDetails_DEFAULT NULL

#define QromaPointManifest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   instanceId,        1) \
X(a, STATIC,   SINGULAR, STRING,   pointName,         2) \
X(a, STATIC,   SINGULAR, STRING,   driverId,          3)
#define QromaPointManifest_CALLBACK NULL
#define QromaPointManifest_DEFAULT NULL

#define QromaDeviceManifest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   deviceName,        1) \
X(a, STATIC,   SINGULAR, UINT32,   pointCount,        2) \
X(a, STATIC,   FIXARRAY, MESSAGE,  qromaPointDetails,   3)
#define QromaDeviceManifest_CALLBACK NULL
#define QromaDeviceManifest_DEFAULT NULL
#define QromaDeviceManifest_qromaPointDetails_MSGTYPE QromaPointDetails

#define QromaDeviceVersion_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   softwareBuildVersion,   1) \
X(a, STATIC,   SINGULAR, STRING,   softwareCompileTime,   2)
#define QromaDeviceVersion_CALLBACK NULL
#define QromaDeviceVersion_DEFAULT NULL

#define QromaCommBtConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   txIntervalInMs,    1) \
X(a, STATIC,   SINGULAR, UINT32,   maxTxMessageSizeInBytes,   2)
#define QromaCommBtConfig_CALLBACK NULL
#define QromaCommBtConfig_DEFAULT NULL

#define QromaDeviceConfig_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  qromaCommBtConfig,   1)
#define QromaDeviceConfig_CALLBACK NULL
#define QromaDeviceConfig_DEFAULT NULL
#define QromaDeviceConfig_qromaCommBtConfig_MSGTYPE QromaCommBtConfig

#define QromaDeviceStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    logLevel,          1) \
X(a, STATIC,   SINGULAR, UENUM,    debugCommMode,     2) \
X(a, STATIC,   SINGULAR, UINT32,   uptimeInMs,        3)
#define QromaDeviceStatus_CALLBACK NULL
#define QromaDeviceStatus_DEFAULT NULL

extern const pb_msgdesc_t QromaPointDetails_msg;
extern const pb_msgdesc_t QromaPointManifest_msg;
extern const pb_msgdesc_t QromaDeviceManifest_msg;
extern const pb_msgdesc_t QromaDeviceVersion_msg;
extern const pb_msgdesc_t QromaCommBtConfig_msg;
extern const pb_msgdesc_t QromaDeviceConfig_msg;
extern const pb_msgdesc_t QromaDeviceStatus_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define QromaPointDetails_fields &QromaPointDetails_msg
#define QromaPointManifest_fields &QromaPointManifest_msg
#define QromaDeviceManifest_fields &QromaDeviceManifest_msg
#define QromaDeviceVersion_fields &QromaDeviceVersion_msg
#define QromaCommBtConfig_fields &QromaCommBtConfig_msg
#define QromaDeviceConfig_fields &QromaDeviceConfig_msg
#define QromaDeviceStatus_fields &QromaDeviceStatus_msg

/* Maximum encoded size of messages (where known) */
#define QromaCommBtConfig_size                   12
#define QromaDeviceConfig_size                   14
#define QromaDeviceManifest_size                 507
#define QromaDeviceStatus_size                   11
#define QromaDeviceVersion_size                  132
#define QromaPointDetails_size                   92
#define QromaPointManifest_size                  56

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
