/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_QROMA_STRIP_COMMAND_PB_H_INCLUDED
#define PB_QROMA_STRIP_COMMAND_PB_H_INCLUDED
#include <pb.h>
#include "qroma-types.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _FactoryResetQromaDevice { 
    char dummy_field;
} FactoryResetQromaDevice;

typedef struct _RestartQromaDevice { 
    char dummy_field;
} RestartQromaDevice;

typedef struct _QpmCommand_SetQromaStripName { 
    char name[30]; 
} QpmCommand_SetQromaStripName;

typedef struct _SetQromaCommMaxTxMessageSizeInBytes { 
    uint32_t maxTxMessageSizeInBytes; 
} SetQromaCommMaxTxMessageSizeInBytes;

typedef struct _SetQromaCommTxIntervalInMs { 
    uint32_t txIntervalInMs; 
} SetQromaCommTxIntervalInMs;

typedef struct _SetQromaDebugCommMode { 
    Qroma_DebugCommMode debugCommMode; 
} SetQromaDebugCommMode;

typedef struct _SetQromaLogLevel { 
    Qroma_LogLevel logLevel; 
} SetQromaLogLevel;

typedef struct _SetQromaStripDeviceName { 
    char name[30]; 
} SetQromaStripDeviceName;

typedef struct _UseCurrentSetupOnStartup { 
    uint32_t delayInMs; 
} UseCurrentSetupOnStartup;

typedef struct _QromaPointManagementCommand { 
    /* uint32 pointIndex = 1; */
    char instanceId[9]; 
    pb_size_t which_qpmCommand;
    union {
        QpmCommand_SetQromaStripName setQromaPointName;
    } qpmCommand; 
} QromaPointManagementCommand;

typedef struct _SetQromaCommConfigCommand { 
    pb_size_t which_setConfigValue;
    union {
        SetQromaCommTxIntervalInMs setQromaCommTxIntervalInMs;
        SetQromaCommMaxTxMessageSizeInBytes setQromaCommMaxTxMessageSizeInBytes;
    } setConfigValue; 
} SetQromaCommConfigCommand;

typedef struct _QromaDeviceCommand { 
    pb_size_t which_command;
    union {
        SetQromaStripDeviceName setQromaStripDeviceName;
        UseCurrentSetupOnStartup useCurrentSetupOnStartup;
        RestartQromaDevice restartQromaDevice;
        FactoryResetQromaDevice factoryResetQromaDevice;
        SetQromaLogLevel setQromaLogLevel;
        SetQromaDebugCommMode setQromaDebugCommMode;
        SetQromaCommConfigCommand setQromaCommConfigCommand;
        QromaPointManagementCommand qromaPointManagementCommand;
    } command; 
} QromaDeviceCommand;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define QpmCommand_SetQromaStripName_init_default {""}
#define QromaPointManagementCommand_init_default {"", 0, {QpmCommand_SetQromaStripName_init_default}}
#define SetQromaStripDeviceName_init_default     {""}
#define UseCurrentSetupOnStartup_init_default    {0}
#define RestartQromaDevice_init_default          {0}
#define SetQromaLogLevel_init_default            {_Qroma_LogLevel_MIN}
#define SetQromaDebugCommMode_init_default       {_Qroma_DebugCommMode_MIN}
#define SetQromaCommTxIntervalInMs_init_default  {0}
#define SetQromaCommMaxTxMessageSizeInBytes_init_default {0}
#define SetQromaCommConfigCommand_init_default   {0, {SetQromaCommTxIntervalInMs_init_default}}
#define FactoryResetQromaDevice_init_default     {0}
#define QromaDeviceCommand_init_default          {0, {SetQromaStripDeviceName_init_default}}
#define QpmCommand_SetQromaStripName_init_zero   {""}
#define QromaPointManagementCommand_init_zero    {"", 0, {QpmCommand_SetQromaStripName_init_zero}}
#define SetQromaStripDeviceName_init_zero        {""}
#define UseCurrentSetupOnStartup_init_zero       {0}
#define RestartQromaDevice_init_zero             {0}
#define SetQromaLogLevel_init_zero               {_Qroma_LogLevel_MIN}
#define SetQromaDebugCommMode_init_zero          {_Qroma_DebugCommMode_MIN}
#define SetQromaCommTxIntervalInMs_init_zero     {0}
#define SetQromaCommMaxTxMessageSizeInBytes_init_zero {0}
#define SetQromaCommConfigCommand_init_zero      {0, {SetQromaCommTxIntervalInMs_init_zero}}
#define FactoryResetQromaDevice_init_zero        {0}
#define QromaDeviceCommand_init_zero             {0, {SetQromaStripDeviceName_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define QpmCommand_SetQromaStripName_name_tag    1
#define SetQromaCommMaxTxMessageSizeInBytes_maxTxMessageSizeInBytes_tag 1
#define SetQromaCommTxIntervalInMs_txIntervalInMs_tag 1
#define SetQromaDebugCommMode_debugCommMode_tag  1
#define SetQromaLogLevel_logLevel_tag            1
#define SetQromaStripDeviceName_name_tag         1
#define UseCurrentSetupOnStartup_delayInMs_tag   1
#define QromaPointManagementCommand_instanceId_tag 1
#define QromaPointManagementCommand_setQromaPointName_tag 2
#define SetQromaCommConfigCommand_setQromaCommTxIntervalInMs_tag 1
#define SetQromaCommConfigCommand_setQromaCommMaxTxMessageSizeInBytes_tag 2
#define QromaDeviceCommand_setQromaStripDeviceName_tag 1
#define QromaDeviceCommand_useCurrentSetupOnStartup_tag 2
#define QromaDeviceCommand_restartQromaDevice_tag 3
#define QromaDeviceCommand_factoryResetQromaDevice_tag 4
#define QromaDeviceCommand_setQromaLogLevel_tag  5
#define QromaDeviceCommand_setQromaDebugCommMode_tag 6
#define QromaDeviceCommand_setQromaCommConfigCommand_tag 7
#define QromaDeviceCommand_qromaPointManagementCommand_tag 50

/* Struct field encoding specification for nanopb */
#define QpmCommand_SetQromaStripName_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1)
#define QpmCommand_SetQromaStripName_CALLBACK NULL
#define QpmCommand_SetQromaStripName_DEFAULT NULL

#define QromaPointManagementCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   instanceId,        1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (qpmCommand,setQromaPointName,qpmCommand.setQromaPointName),   2)
#define QromaPointManagementCommand_CALLBACK NULL
#define QromaPointManagementCommand_DEFAULT NULL
#define QromaPointManagementCommand_qpmCommand_setQromaPointName_MSGTYPE QpmCommand_SetQromaStripName

#define SetQromaStripDeviceName_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1)
#define SetQromaStripDeviceName_CALLBACK NULL
#define SetQromaStripDeviceName_DEFAULT NULL

#define UseCurrentSetupOnStartup_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   delayInMs,         1)
#define UseCurrentSetupOnStartup_CALLBACK NULL
#define UseCurrentSetupOnStartup_DEFAULT NULL

#define RestartQromaDevice_FIELDLIST(X, a) \

#define RestartQromaDevice_CALLBACK NULL
#define RestartQromaDevice_DEFAULT NULL

#define SetQromaLogLevel_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    logLevel,          1)
#define SetQromaLogLevel_CALLBACK NULL
#define SetQromaLogLevel_DEFAULT NULL

#define SetQromaDebugCommMode_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    debugCommMode,     1)
#define SetQromaDebugCommMode_CALLBACK NULL
#define SetQromaDebugCommMode_DEFAULT NULL

#define SetQromaCommTxIntervalInMs_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   txIntervalInMs,    1)
#define SetQromaCommTxIntervalInMs_CALLBACK NULL
#define SetQromaCommTxIntervalInMs_DEFAULT NULL

#define SetQromaCommMaxTxMessageSizeInBytes_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   maxTxMessageSizeInBytes,   1)
#define SetQromaCommMaxTxMessageSizeInBytes_CALLBACK NULL
#define SetQromaCommMaxTxMessageSizeInBytes_DEFAULT NULL

#define SetQromaCommConfigCommand_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (setConfigValue,setQromaCommTxIntervalInMs,setConfigValue.setQromaCommTxIntervalInMs),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (setConfigValue,setQromaCommMaxTxMessageSizeInBytes,setConfigValue.setQromaCommMaxTxMessageSizeInBytes),   2)
#define SetQromaCommConfigCommand_CALLBACK NULL
#define SetQromaCommConfigCommand_DEFAULT NULL
#define SetQromaCommConfigCommand_setConfigValue_setQromaCommTxIntervalInMs_MSGTYPE SetQromaCommTxIntervalInMs
#define SetQromaCommConfigCommand_setConfigValue_setQromaCommMaxTxMessageSizeInBytes_MSGTYPE SetQromaCommMaxTxMessageSizeInBytes

#define FactoryResetQromaDevice_FIELDLIST(X, a) \

#define FactoryResetQromaDevice_CALLBACK NULL
#define FactoryResetQromaDevice_DEFAULT NULL

#define QromaDeviceCommand_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,setQromaStripDeviceName,command.setQromaStripDeviceName),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,useCurrentSetupOnStartup,command.useCurrentSetupOnStartup),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,restartQromaDevice,command.restartQromaDevice),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,factoryResetQromaDevice,command.factoryResetQromaDevice),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,setQromaLogLevel,command.setQromaLogLevel),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,setQromaDebugCommMode,command.setQromaDebugCommMode),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,setQromaCommConfigCommand,command.setQromaCommConfigCommand),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,qromaPointManagementCommand,command.qromaPointManagementCommand),  50)
#define QromaDeviceCommand_CALLBACK NULL
#define QromaDeviceCommand_DEFAULT NULL
#define QromaDeviceCommand_command_setQromaStripDeviceName_MSGTYPE SetQromaStripDeviceName
#define QromaDeviceCommand_command_useCurrentSetupOnStartup_MSGTYPE UseCurrentSetupOnStartup
#define QromaDeviceCommand_command_restartQromaDevice_MSGTYPE RestartQromaDevice
#define QromaDeviceCommand_command_factoryResetQromaDevice_MSGTYPE FactoryResetQromaDevice
#define QromaDeviceCommand_command_setQromaLogLevel_MSGTYPE SetQromaLogLevel
#define QromaDeviceCommand_command_setQromaDebugCommMode_MSGTYPE SetQromaDebugCommMode
#define QromaDeviceCommand_command_setQromaCommConfigCommand_MSGTYPE SetQromaCommConfigCommand
#define QromaDeviceCommand_command_qromaPointManagementCommand_MSGTYPE QromaPointManagementCommand

extern const pb_msgdesc_t QpmCommand_SetQromaStripName_msg;
extern const pb_msgdesc_t QromaPointManagementCommand_msg;
extern const pb_msgdesc_t SetQromaStripDeviceName_msg;
extern const pb_msgdesc_t UseCurrentSetupOnStartup_msg;
extern const pb_msgdesc_t RestartQromaDevice_msg;
extern const pb_msgdesc_t SetQromaLogLevel_msg;
extern const pb_msgdesc_t SetQromaDebugCommMode_msg;
extern const pb_msgdesc_t SetQromaCommTxIntervalInMs_msg;
extern const pb_msgdesc_t SetQromaCommMaxTxMessageSizeInBytes_msg;
extern const pb_msgdesc_t SetQromaCommConfigCommand_msg;
extern const pb_msgdesc_t FactoryResetQromaDevice_msg;
extern const pb_msgdesc_t QromaDeviceCommand_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define QpmCommand_SetQromaStripName_fields &QpmCommand_SetQromaStripName_msg
#define QromaPointManagementCommand_fields &QromaPointManagementCommand_msg
#define SetQromaStripDeviceName_fields &SetQromaStripDeviceName_msg
#define UseCurrentSetupOnStartup_fields &UseCurrentSetupOnStartup_msg
#define RestartQromaDevice_fields &RestartQromaDevice_msg
#define SetQromaLogLevel_fields &SetQromaLogLevel_msg
#define SetQromaDebugCommMode_fields &SetQromaDebugCommMode_msg
#define SetQromaCommTxIntervalInMs_fields &SetQromaCommTxIntervalInMs_msg
#define SetQromaCommMaxTxMessageSizeInBytes_fields &SetQromaCommMaxTxMessageSizeInBytes_msg
#define SetQromaCommConfigCommand_fields &SetQromaCommConfigCommand_msg
#define FactoryResetQromaDevice_fields &FactoryResetQromaDevice_msg
#define QromaDeviceCommand_fields &QromaDeviceCommand_msg

/* Maximum encoded size of messages (where known) */
#define FactoryResetQromaDevice_size             0
#define QpmCommand_SetQromaStripName_size        31
#define QromaDeviceCommand_size                  46
#define QromaPointManagementCommand_size         43
#define RestartQromaDevice_size                  0
#define SetQromaCommConfigCommand_size           8
#define SetQromaCommMaxTxMessageSizeInBytes_size 6
#define SetQromaCommTxIntervalInMs_size          6
#define SetQromaDebugCommMode_size               2
#define SetQromaLogLevel_size                    3
#define SetQromaStripDeviceName_size             31
#define UseCurrentSetupOnStartup_size            6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
