/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "qroma-point-config.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(QromaPointDetails, QromaPointDetails, AUTO)


PB_BIND(QromaPointManifest, QromaPointManifest, AUTO)


PB_BIND(QromaDeviceManifest, QromaDeviceManifest, 2)


PB_BIND(QromaDeviceVersion, QromaDeviceVersion, AUTO)


PB_BIND(QromaCommBtConfig, QromaCommBtConfig, AUTO)


PB_BIND(QromaDeviceConfig, QromaDeviceConfig, AUTO)


PB_BIND(QromaDeviceStatus, QromaDeviceStatus, AUTO)



