/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "file-system-commands.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(DirItem, DirItem, AUTO)


PB_BIND(RmFileCommand, RmFileCommand, AUTO)


PB_BIND(RmFileResponse, RmFileResponse, AUTO)


PB_BIND(RmDirCommand, RmDirCommand, AUTO)


PB_BIND(RmDirResponse, RmDirResponse, AUTO)


PB_BIND(MkDirCommand, MkDirCommand, AUTO)


PB_BIND(MkDirResponse, MkDirResponse, AUTO)


PB_BIND(ReportFileDataCommand, ReportFileDataCommand, AUTO)


PB_BIND(ReportFileDataResponse, ReportFileDataResponse, AUTO)


PB_BIND(ListDirContentsCommand, ListDirContentsCommand, AUTO)


PB_BIND(ListDirContentsResponse, ListDirContentsResponse, 2)


PB_BIND(PrintDirContentsCommand, PrintDirContentsCommand, AUTO)


PB_BIND(ResetFilesystemCommand, ResetFilesystemCommand, AUTO)


PB_BIND(ResetFilesystemResponse, ResetFilesystemResponse, AUTO)


PB_BIND(GetFileContentsCommand, GetFileContentsCommand, AUTO)


PB_BIND(GetFileContentsResponse, GetFileContentsResponse, 4)


PB_BIND(WriteFileDataCommand, WriteFileDataCommand, 4)


PB_BIND(WriteFileDataResponse, WriteFileDataResponse, AUTO)


PB_BIND(FileSystemCommand, FileSystemCommand, 4)


PB_BIND(FileSystemResponse, FileSystemResponse, 4)





