/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "qroma-comm-config-commands.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(RequestQromaCommConfig, RequestQromaCommConfig, AUTO)


PB_BIND(QromaCommConfig, QromaCommConfig, AUTO)


PB_BIND(SetLogLevelRequest, SetLogLevelRequest, AUTO)


PB_BIND(SetLogLevelResponse, SetLogLevelResponse, AUTO)


PB_BIND(SetHeartbeatIntervalRequest, SetHeartbeatIntervalRequest, AUTO)


PB_BIND(SetHeartbeatIntervalResponse, SetHeartbeatIntervalResponse, AUTO)


PB_BIND(QromaCommConfigCommand, QromaCommConfigCommand, AUTO)


PB_BIND(QromaCommConfigResponse, QromaCommConfigResponse, AUTO)



