/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_QROMA_CONFIG_PB_H_INCLUDED
#define PB_QROMA_CONFIG_PB_H_INCLUDED
#include <pb.h>
#include "qroma-types.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _HeartbeatConfiguration { 
    HeartbeatType heartbeatType; 
    uint32_t heartbeatIntervalInMs; 
} HeartbeatConfiguration;

typedef struct _QromaCommSerialIoConfig { 
    uint32_t baudRate; 
    uint32_t rxBufferSize; 
    uint32_t txBufferSize; 
} QromaCommSerialIoConfig;

typedef struct _QromaCommSerialProcessingConfig { 
    uint32_t msDelayInProcessingLoop; 
} QromaCommSerialProcessingConfig;

typedef struct _QromaCoreLoggingConfig { 
    Qroma_LogLevel logLevel; 
} QromaCoreLoggingConfig;

typedef struct _QromaCoreManagementConfiguration { 
    uint32_t projectLoopDelayInMs; 
    bool has_heartbeatConfiguration;
    HeartbeatConfiguration heartbeatConfiguration; 
} QromaCoreManagementConfiguration;

typedef struct _QromaCoreConfig { 
    bool has_serialIoConfig;
    QromaCommSerialIoConfig serialIoConfig; 
    bool has_serialProcessingConfig;
    QromaCommSerialProcessingConfig serialProcessingConfig; 
    bool has_loggingConfig;
    QromaCoreLoggingConfig loggingConfig; 
    bool has_managementConfig;
    QromaCoreManagementConfiguration managementConfig; 
} QromaCoreConfig;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define QromaCommSerialIoConfig_init_default     {0, 0, 0}
#define QromaCommSerialProcessingConfig_init_default {0}
#define QromaCoreLoggingConfig_init_default      {_Qroma_LogLevel_MIN}
#define HeartbeatConfiguration_init_default      {_HeartbeatType_MIN, 0}
#define QromaCoreManagementConfiguration_init_default {0, false, HeartbeatConfiguration_init_default}
#define QromaCoreConfig_init_default             {false, QromaCommSerialIoConfig_init_default, false, QromaCommSerialProcessingConfig_init_default, false, QromaCoreLoggingConfig_init_default, false, QromaCoreManagementConfiguration_init_default}
#define QromaCommSerialIoConfig_init_zero        {0, 0, 0}
#define QromaCommSerialProcessingConfig_init_zero {0}
#define QromaCoreLoggingConfig_init_zero         {_Qroma_LogLevel_MIN}
#define HeartbeatConfiguration_init_zero         {_HeartbeatType_MIN, 0}
#define QromaCoreManagementConfiguration_init_zero {0, false, HeartbeatConfiguration_init_zero}
#define QromaCoreConfig_init_zero                {false, QromaCommSerialIoConfig_init_zero, false, QromaCommSerialProcessingConfig_init_zero, false, QromaCoreLoggingConfig_init_zero, false, QromaCoreManagementConfiguration_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define HeartbeatConfiguration_heartbeatType_tag 1
#define HeartbeatConfiguration_heartbeatIntervalInMs_tag 2
#define QromaCommSerialIoConfig_baudRate_tag     1
#define QromaCommSerialIoConfig_rxBufferSize_tag 2
#define QromaCommSerialIoConfig_txBufferSize_tag 3
#define QromaCommSerialProcessingConfig_msDelayInProcessingLoop_tag 1
#define QromaCoreLoggingConfig_logLevel_tag      1
#define QromaCoreManagementConfiguration_projectLoopDelayInMs_tag 1
#define QromaCoreManagementConfiguration_heartbeatConfiguration_tag 2
#define QromaCoreConfig_serialIoConfig_tag       1
#define QromaCoreConfig_serialProcessingConfig_tag 2
#define QromaCoreConfig_loggingConfig_tag        3
#define QromaCoreConfig_managementConfig_tag     4

/* Struct field encoding specification for nanopb */
#define QromaCommSerialIoConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   baudRate,          1) \
X(a, STATIC,   SINGULAR, UINT32,   rxBufferSize,      2) \
X(a, STATIC,   SINGULAR, UINT32,   txBufferSize,      3)
#define QromaCommSerialIoConfig_CALLBACK NULL
#define QromaCommSerialIoConfig_DEFAULT NULL

#define QromaCommSerialProcessingConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   msDelayInProcessingLoop,   1)
#define QromaCommSerialProcessingConfig_CALLBACK NULL
#define QromaCommSerialProcessingConfig_DEFAULT NULL

#define QromaCoreLoggingConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    logLevel,          1)
#define QromaCoreLoggingConfig_CALLBACK NULL
#define QromaCoreLoggingConfig_DEFAULT NULL

#define HeartbeatConfiguration_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    heartbeatType,     1) \
X(a, STATIC,   SINGULAR, UINT32,   heartbeatIntervalInMs,   2)
#define HeartbeatConfiguration_CALLBACK NULL
#define HeartbeatConfiguration_DEFAULT NULL

#define QromaCoreManagementConfiguration_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   projectLoopDelayInMs,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  heartbeatConfiguration,   2)
#define QromaCoreManagementConfiguration_CALLBACK NULL
#define QromaCoreManagementConfiguration_DEFAULT NULL
#define QromaCoreManagementConfiguration_heartbeatConfiguration_MSGTYPE HeartbeatConfiguration

#define QromaCoreConfig_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  serialIoConfig,    1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  serialProcessingConfig,   2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  loggingConfig,     3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  managementConfig,   4)
#define QromaCoreConfig_CALLBACK NULL
#define QromaCoreConfig_DEFAULT NULL
#define QromaCoreConfig_serialIoConfig_MSGTYPE QromaCommSerialIoConfig
#define QromaCoreConfig_serialProcessingConfig_MSGTYPE QromaCommSerialProcessingConfig
#define QromaCoreConfig_loggingConfig_MSGTYPE QromaCoreLoggingConfig
#define QromaCoreConfig_managementConfig_MSGTYPE QromaCoreManagementConfiguration

extern const pb_msgdesc_t QromaCommSerialIoConfig_msg;
extern const pb_msgdesc_t QromaCommSerialProcessingConfig_msg;
extern const pb_msgdesc_t QromaCoreLoggingConfig_msg;
extern const pb_msgdesc_t HeartbeatConfiguration_msg;
extern const pb_msgdesc_t QromaCoreManagementConfiguration_msg;
extern const pb_msgdesc_t QromaCoreConfig_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define QromaCommSerialIoConfig_fields &QromaCommSerialIoConfig_msg
#define QromaCommSerialProcessingConfig_fields &QromaCommSerialProcessingConfig_msg
#define QromaCoreLoggingConfig_fields &QromaCoreLoggingConfig_msg
#define HeartbeatConfiguration_fields &HeartbeatConfiguration_msg
#define QromaCoreManagementConfiguration_fields &QromaCoreManagementConfiguration_msg
#define QromaCoreConfig_fields &QromaCoreConfig_msg

/* Maximum encoded size of messages (where known) */
#define HeartbeatConfiguration_size              8
#define QromaCommSerialIoConfig_size             18
#define QromaCommSerialProcessingConfig_size     6
#define QromaCoreConfig_size                     51
#define QromaCoreLoggingConfig_size              3
#define QromaCoreManagementConfiguration_size    16

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
