/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "qroma-streams.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(InitWriteFileStreamCommand, InitWriteFileStreamCommand, AUTO)


PB_BIND(InitWriteFileStreamAckResponse, InitWriteFileStreamAckResponse, AUTO)


PB_BIND(WriteFileStreamCompleteResponse, WriteFileStreamCompleteResponse, AUTO)


PB_BIND(QromaStreamCommand, QromaStreamCommand, AUTO)


PB_BIND(QromaStreamResponse, QromaStreamResponse, AUTO)



