/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "qroma-config.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(QromaCommSerialIoConfig, QromaCommSerialIoConfig, AUTO)


PB_BIND(QromaCommSerialProcessingConfig, QromaCommSerialProcessingConfig, AUTO)


PB_BIND(QromaCoreLoggingConfig, QromaCoreLoggingConfig, AUTO)


PB_BIND(HeartbeatConfiguration, HeartbeatConfiguration, AUTO)


PB_BIND(QromaCoreManagementConfiguration, QromaCoreManagementConfiguration, AUTO)


PB_BIND(QromaCoreConfig, QromaCoreConfig, AUTO)



