/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "qroma-core.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(GetQromaCoreConfigCommand, GetQromaCoreConfigCommand, AUTO)


PB_BIND(GetQromaCoreFirmwareDetailsCommand, GetQromaCoreFirmwareDetailsCommand, AUTO)


PB_BIND(RestartQromaDeviceCommand, RestartQromaDeviceCommand, AUTO)


PB_BIND(RestartQromaDeviceAck, RestartQromaDeviceAck, AUTO)


PB_BIND(SetQromaCommSerialIoConfigCommand, SetQromaCommSerialIoConfigCommand, AUTO)


PB_BIND(SetQromaCommSerialProcessingConfig, SetQromaCommSerialProcessingConfig, AUTO)


PB_BIND(SetQromaCoreLoggingConfigCommand, SetQromaCoreLoggingConfigCommand, AUTO)


PB_BIND(SetHeartbeatConfigurationCommand, SetHeartbeatConfigurationCommand, AUTO)


PB_BIND(SetQromaCoreManagementConfiguration, SetQromaCoreManagementConfiguration, AUTO)


PB_BIND(QromaCoreCommand, QromaCoreCommand, AUTO)


PB_BIND(QromaCoreResponse, QromaCoreResponse, AUTO)




