/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "qroma-power-settings.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(QromaPower_DevPowerMode, QromaPower_DevPowerMode, AUTO)


PB_BIND(QromaPower_Config, QromaPower_Config, AUTO)


PB_BIND(QromaPower_Status, QromaPower_Status, AUTO)


PB_BIND(SetPowerCheckIntervalInMsCommand, SetPowerCheckIntervalInMsCommand, AUTO)


PB_BIND(SetBatteryIsChargedThresholdInVoltsCommand, SetBatteryIsChargedThresholdInVoltsCommand, AUTO)


PB_BIND(SetLowBatteryVoltageInVoltsCommand, SetLowBatteryVoltageInVoltsCommand, AUTO)


PB_BIND(SetStopNormalOpsBatteryVoltageInVoltsCommand, SetStopNormalOpsBatteryVoltageInVoltsCommand, AUTO)


PB_BIND(SetHasOnboardBatteryCommand, SetHasOnboardBatteryCommand, AUTO)


PB_BIND(SetPowerConfigurationCommand, SetPowerConfigurationCommand, AUTO)


PB_BIND(QromaPower_Command, QromaPower_Command, AUTO)




