/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_QROMA_COMM_PB_H_INCLUDED
#define PB_QROMA_COMM_PB_H_INCLUDED
#include <pb.h>
#include "file-system-commands.pb.h"
#include "qroma-comm-config-commands.pb.h"
#include "qroma-streams.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(1000) QromaCommCommand_appCommandBytes_t;
typedef struct _QromaCommCommand { 
    pb_size_t which_command;
    union {
        QromaCommCommand_appCommandBytes_t appCommandBytes;
        FileSystemCommand fsCommand;
        QromaCommConfigCommand commConfigCommand;
        QromaStreamCommand streamCommand;
    } command; 
} QromaCommCommand;

typedef struct _QromaCommHeartbeatResponse { 
    uint32_t uptimeInMs; 
    uint32_t heartbeatTicks; 
} QromaCommHeartbeatResponse;

typedef PB_BYTES_ARRAY_T(1000) QromaCommResponse_appResponseBytes_t;
typedef struct _QromaCommResponse { 
    pb_size_t which_response;
    union {
        QromaCommResponse_appResponseBytes_t appResponseBytes;
        FileSystemResponse fsResponse;
        QromaCommConfigResponse commConfigResponse;
        QromaCommHeartbeatResponse heartbeatResponse;
        QromaStreamResponse streamResponse;
    } response; 
} QromaCommResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define QromaCommCommand_init_default            {0, {{0, {0}}}}
#define QromaCommHeartbeatResponse_init_default  {0, 0}
#define QromaCommResponse_init_default           {0, {{0, {0}}}}
#define QromaCommCommand_init_zero               {0, {{0, {0}}}}
#define QromaCommHeartbeatResponse_init_zero     {0, 0}
#define QromaCommResponse_init_zero              {0, {{0, {0}}}}

/* Field tags (for use in manual encoding/decoding) */
#define QromaCommCommand_appCommandBytes_tag     1
#define QromaCommCommand_fsCommand_tag           2
#define QromaCommCommand_commConfigCommand_tag   3
#define QromaCommCommand_streamCommand_tag       4
#define QromaCommHeartbeatResponse_uptimeInMs_tag 1
#define QromaCommHeartbeatResponse_heartbeatTicks_tag 2
#define QromaCommResponse_appResponseBytes_tag   1
#define QromaCommResponse_fsResponse_tag         2
#define QromaCommResponse_commConfigResponse_tag 3
#define QromaCommResponse_heartbeatResponse_tag  4
#define QromaCommResponse_streamResponse_tag     5

/* Struct field encoding specification for nanopb */
#define QromaCommCommand_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    BYTES,    (command,appCommandBytes,command.appCommandBytes),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,fsCommand,command.fsCommand),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,commConfigCommand,command.commConfigCommand),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,streamCommand,command.streamCommand),   4)
#define QromaCommCommand_CALLBACK NULL
#define QromaCommCommand_DEFAULT NULL
#define QromaCommCommand_command_fsCommand_MSGTYPE FileSystemCommand
#define QromaCommCommand_command_commConfigCommand_MSGTYPE QromaCommConfigCommand
#define QromaCommCommand_command_streamCommand_MSGTYPE QromaStreamCommand

#define QromaCommHeartbeatResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   uptimeInMs,        1) \
X(a, STATIC,   SINGULAR, UINT32,   heartbeatTicks,    2)
#define QromaCommHeartbeatResponse_CALLBACK NULL
#define QromaCommHeartbeatResponse_DEFAULT NULL

#define QromaCommResponse_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    BYTES,    (response,appResponseBytes,response.appResponseBytes),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,fsResponse,response.fsResponse),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,commConfigResponse,response.commConfigResponse),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,heartbeatResponse,response.heartbeatResponse),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,streamResponse,response.streamResponse),   5)
#define QromaCommResponse_CALLBACK NULL
#define QromaCommResponse_DEFAULT NULL
#define QromaCommResponse_response_fsResponse_MSGTYPE FileSystemResponse
#define QromaCommResponse_response_commConfigResponse_MSGTYPE QromaCommConfigResponse
#define QromaCommResponse_response_heartbeatResponse_MSGTYPE QromaCommHeartbeatResponse
#define QromaCommResponse_response_streamResponse_MSGTYPE QromaStreamResponse

extern const pb_msgdesc_t QromaCommCommand_msg;
extern const pb_msgdesc_t QromaCommHeartbeatResponse_msg;
extern const pb_msgdesc_t QromaCommResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define QromaCommCommand_fields &QromaCommCommand_msg
#define QromaCommHeartbeatResponse_fields &QromaCommHeartbeatResponse_msg
#define QromaCommResponse_fields &QromaCommResponse_msg

/* Maximum encoded size of messages (where known) */
#define QromaCommCommand_size                    5056
#define QromaCommHeartbeatResponse_size          12
#define QromaCommResponse_size                   5058

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
