/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "qroma-strip-command.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(QpmCommand_SetQromaStripName, QpmCommand_SetQromaStripName, AUTO)


PB_BIND(QromaPointManagementCommand, QromaPointManagementCommand, AUTO)


PB_BIND(SetQromaStripDeviceName, SetQromaStripDeviceName, AUTO)


PB_BIND(UseCurrentSetupOnStartup, UseCurrentSetupOnStartup, AUTO)


PB_BIND(RestartQromaDevice, RestartQromaDevice, AUTO)


PB_BIND(SetQromaLogLevel, SetQromaLogLevel, AUTO)


PB_BIND(SetQromaDebugCommMode, SetQromaDebugCommMode, AUTO)


PB_BIND(SetQromaCommTxIntervalInMs, SetQromaCommTxIntervalInMs, AUTO)


PB_BIND(SetQromaCommMaxTxMessageSizeInBytes, SetQromaCommMaxTxMessageSizeInBytes, AUTO)


PB_BIND(SetQromaCommConfigCommand, SetQromaCommConfigCommand, AUTO)


PB_BIND(FactoryResetQromaDevice, FactoryResetQromaDevice, AUTO)


PB_BIND(QromaDeviceCommand, QromaDeviceCommand, AUTO)



