/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_QROMA_COMM_CONFIG_COMMANDS_PB_H_INCLUDED
#define PB_QROMA_COMM_CONFIG_COMMANDS_PB_H_INCLUDED
#include <pb.h>
#include "qroma-types.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _SetLogLevel { 
    Qroma_LogLevel logLevel; 
} SetLogLevel;

typedef struct _QromaCommConfigCommand { 
    pb_size_t which_command;
    union {
        SetLogLevel setLogLevel;
    } command; 
} QromaCommConfigCommand;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SetLogLevel_init_default                 {_Qroma_LogLevel_MIN}
#define QromaCommConfigCommand_init_default      {0, {SetLogLevel_init_default}}
#define SetLogLevel_init_zero                    {_Qroma_LogLevel_MIN}
#define QromaCommConfigCommand_init_zero         {0, {SetLogLevel_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define SetLogLevel_logLevel_tag                 1
#define QromaCommConfigCommand_setLogLevel_tag   1

/* Struct field encoding specification for nanopb */
#define SetLogLevel_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    logLevel,          1)
#define SetLogLevel_CALLBACK NULL
#define SetLogLevel_DEFAULT NULL

#define QromaCommConfigCommand_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,setLogLevel,command.setLogLevel),   1)
#define QromaCommConfigCommand_CALLBACK NULL
#define QromaCommConfigCommand_DEFAULT NULL
#define QromaCommConfigCommand_command_setLogLevel_MSGTYPE SetLogLevel

extern const pb_msgdesc_t SetLogLevel_msg;
extern const pb_msgdesc_t QromaCommConfigCommand_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SetLogLevel_fields &SetLogLevel_msg
#define QromaCommConfigCommand_fields &QromaCommConfigCommand_msg

/* Maximum encoded size of messages (where known) */
#define QromaCommConfigCommand_size              5
#define SetLogLevel_size                         3

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
