/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_QROMA_CORE_PB_H_INCLUDED
#define PB_QROMA_CORE_PB_H_INCLUDED
#include <pb.h>
#include "qroma-types.pb.h"
#include "qroma-config.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _GetQromaCoreConfigCommand { 
    uint32_t ignoreThis; 
} GetQromaCoreConfigCommand;

typedef struct _GetQromaCoreFirmwareDetailsCommand { 
    uint32_t ignoreThis; 
} GetQromaCoreFirmwareDetailsCommand;

typedef struct _RestartQromaDeviceAck { 
    uint32_t ignoreThis; 
} RestartQromaDeviceAck;

typedef struct _RestartQromaDeviceCommand { 
    uint32_t ignoreThis; 
} RestartQromaDeviceCommand;

typedef struct _SetHeartbeatConfigurationCommand { 
    bool has_config;
    HeartbeatConfiguration config; 
} SetHeartbeatConfigurationCommand;

typedef struct _SetQromaCommSerialIoConfigCommand { 
    bool has_config;
    QromaCommSerialIoConfig config; 
} SetQromaCommSerialIoConfigCommand;

typedef struct _SetQromaCommSerialProcessingConfig { 
    bool has_config;
    QromaCommSerialProcessingConfig config; 
} SetQromaCommSerialProcessingConfig;

typedef struct _SetQromaCoreLoggingConfigCommand { 
    bool has_config;
    QromaCoreLoggingConfig config; 
} SetQromaCoreLoggingConfigCommand;

typedef struct _SetQromaProjectConfiguration { 
    bool has_config;
    QromaProjectConfiguration config; 
} SetQromaProjectConfiguration;

typedef struct _QromaCoreCommand { 
    pb_size_t which_command;
    union {
        GetQromaCoreConfigCommand getQromaCoreConfig;
        GetQromaCoreFirmwareDetailsCommand getFirmwareDetails;
        RestartQromaDeviceCommand restartQromaDevice;
        SetQromaCommSerialIoConfigCommand setQromaCommSerialIoConfig;
        SetQromaCommSerialProcessingConfig setQromaCommSerialProcessingConfig;
        SetQromaCoreLoggingConfigCommand setQromaCoreLoggingConfig;
        SetQromaProjectConfiguration setQromaProjectConfiguration;
    } command; 
} QromaCoreCommand;

typedef struct _QromaCoreResponse { 
    pb_size_t which_response;
    union {
        QromaCoreConfig qromaCoreConfig;
        HeartbeatResponse heartbeat;
        FirmwareDetails firmwareDetails;
        RestartQromaDeviceAck restartAck;
    } response; 
} QromaCoreResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define GetQromaCoreConfigCommand_init_default   {0}
#define GetQromaCoreFirmwareDetailsCommand_init_default {0}
#define RestartQromaDeviceCommand_init_default   {0}
#define RestartQromaDeviceAck_init_default       {0}
#define SetQromaCommSerialIoConfigCommand_init_default {false, QromaCommSerialIoConfig_init_default}
#define SetQromaCommSerialProcessingConfig_init_default {false, QromaCommSerialProcessingConfig_init_default}
#define SetQromaCoreLoggingConfigCommand_init_default {false, QromaCoreLoggingConfig_init_default}
#define SetHeartbeatConfigurationCommand_init_default {false, HeartbeatConfiguration_init_default}
#define SetQromaProjectConfiguration_init_default {false, QromaProjectConfiguration_init_default}
#define QromaCoreCommand_init_default            {0, {GetQromaCoreConfigCommand_init_default}}
#define QromaCoreResponse_init_default           {0, {QromaCoreConfig_init_default}}
#define GetQromaCoreConfigCommand_init_zero      {0}
#define GetQromaCoreFirmwareDetailsCommand_init_zero {0}
#define RestartQromaDeviceCommand_init_zero      {0}
#define RestartQromaDeviceAck_init_zero          {0}
#define SetQromaCommSerialIoConfigCommand_init_zero {false, QromaCommSerialIoConfig_init_zero}
#define SetQromaCommSerialProcessingConfig_init_zero {false, QromaCommSerialProcessingConfig_init_zero}
#define SetQromaCoreLoggingConfigCommand_init_zero {false, QromaCoreLoggingConfig_init_zero}
#define SetHeartbeatConfigurationCommand_init_zero {false, HeartbeatConfiguration_init_zero}
#define SetQromaProjectConfiguration_init_zero   {false, QromaProjectConfiguration_init_zero}
#define QromaCoreCommand_init_zero               {0, {GetQromaCoreConfigCommand_init_zero}}
#define QromaCoreResponse_init_zero              {0, {QromaCoreConfig_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define GetQromaCoreConfigCommand_ignoreThis_tag 1
#define GetQromaCoreFirmwareDetailsCommand_ignoreThis_tag 1
#define RestartQromaDeviceAck_ignoreThis_tag     1
#define RestartQromaDeviceCommand_ignoreThis_tag 1
#define SetHeartbeatConfigurationCommand_config_tag 1
#define SetQromaCommSerialIoConfigCommand_config_tag 1
#define SetQromaCommSerialProcessingConfig_config_tag 1
#define SetQromaCoreLoggingConfigCommand_config_tag 1
#define SetQromaProjectConfiguration_config_tag  1
#define QromaCoreCommand_getQromaCoreConfig_tag  1
#define QromaCoreCommand_getFirmwareDetails_tag  2
#define QromaCoreCommand_restartQromaDevice_tag  3
#define QromaCoreCommand_setQromaCommSerialIoConfig_tag 4
#define QromaCoreCommand_setQromaCommSerialProcessingConfig_tag 5
#define QromaCoreCommand_setQromaCoreLoggingConfig_tag 6
#define QromaCoreCommand_setQromaProjectConfiguration_tag 7
#define QromaCoreResponse_qromaCoreConfig_tag    1
#define QromaCoreResponse_heartbeat_tag          2
#define QromaCoreResponse_firmwareDetails_tag    3
#define QromaCoreResponse_restartAck_tag         4

/* Struct field encoding specification for nanopb */
#define GetQromaCoreConfigCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ignoreThis,        1)
#define GetQromaCoreConfigCommand_CALLBACK NULL
#define GetQromaCoreConfigCommand_DEFAULT NULL

#define GetQromaCoreFirmwareDetailsCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ignoreThis,        1)
#define GetQromaCoreFirmwareDetailsCommand_CALLBACK NULL
#define GetQromaCoreFirmwareDetailsCommand_DEFAULT NULL

#define RestartQromaDeviceCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ignoreThis,        1)
#define RestartQromaDeviceCommand_CALLBACK NULL
#define RestartQromaDeviceCommand_DEFAULT NULL

#define RestartQromaDeviceAck_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ignoreThis,        1)
#define RestartQromaDeviceAck_CALLBACK NULL
#define RestartQromaDeviceAck_DEFAULT NULL

#define SetQromaCommSerialIoConfigCommand_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  config,            1)
#define SetQromaCommSerialIoConfigCommand_CALLBACK NULL
#define SetQromaCommSerialIoConfigCommand_DEFAULT NULL
#define SetQromaCommSerialIoConfigCommand_config_MSGTYPE QromaCommSerialIoConfig

#define SetQromaCommSerialProcessingConfig_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  config,            1)
#define SetQromaCommSerialProcessingConfig_CALLBACK NULL
#define SetQromaCommSerialProcessingConfig_DEFAULT NULL
#define SetQromaCommSerialProcessingConfig_config_MSGTYPE QromaCommSerialProcessingConfig

#define SetQromaCoreLoggingConfigCommand_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  config,            1)
#define SetQromaCoreLoggingConfigCommand_CALLBACK NULL
#define SetQromaCoreLoggingConfigCommand_DEFAULT NULL
#define SetQromaCoreLoggingConfigCommand_config_MSGTYPE QromaCoreLoggingConfig

#define SetHeartbeatConfigurationCommand_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  config,            1)
#define SetHeartbeatConfigurationCommand_CALLBACK NULL
#define SetHeartbeatConfigurationCommand_DEFAULT NULL
#define SetHeartbeatConfigurationCommand_config_MSGTYPE HeartbeatConfiguration

#define SetQromaProjectConfiguration_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  config,            1)
#define SetQromaProjectConfiguration_CALLBACK NULL
#define SetQromaProjectConfiguration_DEFAULT NULL
#define SetQromaProjectConfiguration_config_MSGTYPE QromaProjectConfiguration

#define QromaCoreCommand_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,getQromaCoreConfig,command.getQromaCoreConfig),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,getFirmwareDetails,command.getFirmwareDetails),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,restartQromaDevice,command.restartQromaDevice),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,setQromaCommSerialIoConfig,command.setQromaCommSerialIoConfig),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,setQromaCommSerialProcessingConfig,command.setQromaCommSerialProcessingConfig),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,setQromaCoreLoggingConfig,command.setQromaCoreLoggingConfig),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,setQromaProjectConfiguration,command.setQromaProjectConfiguration),   7)
#define QromaCoreCommand_CALLBACK NULL
#define QromaCoreCommand_DEFAULT NULL
#define QromaCoreCommand_command_getQromaCoreConfig_MSGTYPE GetQromaCoreConfigCommand
#define QromaCoreCommand_command_getFirmwareDetails_MSGTYPE GetQromaCoreFirmwareDetailsCommand
#define QromaCoreCommand_command_restartQromaDevice_MSGTYPE RestartQromaDeviceCommand
#define QromaCoreCommand_command_setQromaCommSerialIoConfig_MSGTYPE SetQromaCommSerialIoConfigCommand
#define QromaCoreCommand_command_setQromaCommSerialProcessingConfig_MSGTYPE SetQromaCommSerialProcessingConfig
#define QromaCoreCommand_command_setQromaCoreLoggingConfig_MSGTYPE SetQromaCoreLoggingConfigCommand
#define QromaCoreCommand_command_setQromaProjectConfiguration_MSGTYPE SetQromaProjectConfiguration

#define QromaCoreResponse_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,qromaCoreConfig,response.qromaCoreConfig),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,heartbeat,response.heartbeat),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,firmwareDetails,response.firmwareDetails),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,restartAck,response.restartAck),   4)
#define QromaCoreResponse_CALLBACK NULL
#define QromaCoreResponse_DEFAULT NULL
#define QromaCoreResponse_response_qromaCoreConfig_MSGTYPE QromaCoreConfig
#define QromaCoreResponse_response_heartbeat_MSGTYPE HeartbeatResponse
#define QromaCoreResponse_response_firmwareDetails_MSGTYPE FirmwareDetails
#define QromaCoreResponse_response_restartAck_MSGTYPE RestartQromaDeviceAck

extern const pb_msgdesc_t GetQromaCoreConfigCommand_msg;
extern const pb_msgdesc_t GetQromaCoreFirmwareDetailsCommand_msg;
extern const pb_msgdesc_t RestartQromaDeviceCommand_msg;
extern const pb_msgdesc_t RestartQromaDeviceAck_msg;
extern const pb_msgdesc_t SetQromaCommSerialIoConfigCommand_msg;
extern const pb_msgdesc_t SetQromaCommSerialProcessingConfig_msg;
extern const pb_msgdesc_t SetQromaCoreLoggingConfigCommand_msg;
extern const pb_msgdesc_t SetHeartbeatConfigurationCommand_msg;
extern const pb_msgdesc_t SetQromaProjectConfiguration_msg;
extern const pb_msgdesc_t QromaCoreCommand_msg;
extern const pb_msgdesc_t QromaCoreResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define GetQromaCoreConfigCommand_fields &GetQromaCoreConfigCommand_msg
#define GetQromaCoreFirmwareDetailsCommand_fields &GetQromaCoreFirmwareDetailsCommand_msg
#define RestartQromaDeviceCommand_fields &RestartQromaDeviceCommand_msg
#define RestartQromaDeviceAck_fields &RestartQromaDeviceAck_msg
#define SetQromaCommSerialIoConfigCommand_fields &SetQromaCommSerialIoConfigCommand_msg
#define SetQromaCommSerialProcessingConfig_fields &SetQromaCommSerialProcessingConfig_msg
#define SetQromaCoreLoggingConfigCommand_fields &SetQromaCoreLoggingConfigCommand_msg
#define SetHeartbeatConfigurationCommand_fields &SetHeartbeatConfigurationCommand_msg
#define SetQromaProjectConfiguration_fields &SetQromaProjectConfiguration_msg
#define QromaCoreCommand_fields &QromaCoreCommand_msg
#define QromaCoreResponse_fields &QromaCoreResponse_msg

/* Maximum encoded size of messages (where known) */
#define GetQromaCoreConfigCommand_size           6
#define GetQromaCoreFirmwareDetailsCommand_size  6
#define QromaCoreCommand_size                    22
#define QromaCoreResponse_size                   156
#define RestartQromaDeviceAck_size               6
#define RestartQromaDeviceCommand_size           6
#define SetHeartbeatConfigurationCommand_size    10
#define SetQromaCommSerialIoConfigCommand_size   20
#define SetQromaCommSerialProcessingConfig_size  8
#define SetQromaCoreLoggingConfigCommand_size    5
#define SetQromaProjectConfiguration_size        18

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
