/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_QROMA_COMM_PB_H_INCLUDED
#define PB_QROMA_COMM_PB_H_INCLUDED
#include <pb.h>
#include "file-system-commands.pb.h"
#include "qroma-comm-config-commands.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _QromaCommCommand { 
    pb_size_t which_command;
    union {
        pb_callback_t appCommand;
        FileSystemCommand fsCommand;
        QromaCommConfigCommand commConfigCommand;
    } command; 
} QromaCommCommand;

typedef struct _QromaCommResponse { 
    pb_size_t which_response;
    union {
        pb_callback_t appResponse;
        FileSystemResponse fsResponse;
        QromaCommConfigCommand commConfigResponse;
    } response; 
} QromaCommResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define QromaCommCommand_init_default            {0, {{{NULL}, NULL}}}
#define QromaCommResponse_init_default           {0, {{{NULL}, NULL}}}
#define QromaCommCommand_init_zero               {0, {{{NULL}, NULL}}}
#define QromaCommResponse_init_zero              {0, {{{NULL}, NULL}}}

/* Field tags (for use in manual encoding/decoding) */
#define QromaCommCommand_appCommand_tag          1
#define QromaCommCommand_fsCommand_tag           2
#define QromaCommCommand_commConfigCommand_tag   3
#define QromaCommResponse_appResponse_tag        1
#define QromaCommResponse_fsResponse_tag         2
#define QromaCommResponse_commConfigResponse_tag 3

/* Struct field encoding specification for nanopb */
#define QromaCommCommand_FIELDLIST(X, a) \
X(a, CALLBACK, ONEOF,    BYTES,    (command,appCommand,command.appCommand),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,fsCommand,command.fsCommand),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,commConfigCommand,command.commConfigCommand),   3)
#define QromaCommCommand_CALLBACK pb_default_field_callback
#define QromaCommCommand_DEFAULT NULL
#define QromaCommCommand_command_fsCommand_MSGTYPE FileSystemCommand
#define QromaCommCommand_command_commConfigCommand_MSGTYPE QromaCommConfigCommand

#define QromaCommResponse_FIELDLIST(X, a) \
X(a, CALLBACK, ONEOF,    BYTES,    (response,appResponse,response.appResponse),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,fsResponse,response.fsResponse),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,commConfigResponse,response.commConfigResponse),   3)
#define QromaCommResponse_CALLBACK pb_default_field_callback
#define QromaCommResponse_DEFAULT NULL
#define QromaCommResponse_response_fsResponse_MSGTYPE FileSystemResponse
#define QromaCommResponse_response_commConfigResponse_MSGTYPE QromaCommConfigCommand

extern const pb_msgdesc_t QromaCommCommand_msg;
extern const pb_msgdesc_t QromaCommResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define QromaCommCommand_fields &QromaCommCommand_msg
#define QromaCommResponse_fields &QromaCommResponse_msg

/* Maximum encoded size of messages (where known) */
/* QromaCommCommand_size depends on runtime parameters */
/* QromaCommResponse_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
