/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_QROMA_CONFIG_PB_H_INCLUDED
#define PB_QROMA_CONFIG_PB_H_INCLUDED
#include <pb.h>
#include "qroma-types.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _QromaCommReportingConfig { 
    Qroma_LogLevel logLevel; 
    uint32_t heartbeatIntervalInMs; 
} QromaCommReportingConfig;

typedef struct _QromaCommSerialIoConfig { 
    uint32_t baudRate; 
    uint32_t rxBufferSize; 
    uint32_t txBufferSize; 
} QromaCommSerialIoConfig;

typedef struct _QromaCommConfig { 
    bool has_serialIoConfig;
    QromaCommSerialIoConfig serialIoConfig; 
    bool has_reportingConfig;
    QromaCommReportingConfig reportingConfig; 
} QromaCommConfig;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define QromaCommSerialIoConfig_init_default     {0, 0, 0}
#define QromaCommReportingConfig_init_default    {_Qroma_LogLevel_MIN, 0}
#define QromaCommConfig_init_default             {false, QromaCommSerialIoConfig_init_default, false, QromaCommReportingConfig_init_default}
#define QromaCommSerialIoConfig_init_zero        {0, 0, 0}
#define QromaCommReportingConfig_init_zero       {_Qroma_LogLevel_MIN, 0}
#define QromaCommConfig_init_zero                {false, QromaCommSerialIoConfig_init_zero, false, QromaCommReportingConfig_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define QromaCommReportingConfig_logLevel_tag    1
#define QromaCommReportingConfig_heartbeatIntervalInMs_tag 2
#define QromaCommSerialIoConfig_baudRate_tag     1
#define QromaCommSerialIoConfig_rxBufferSize_tag 2
#define QromaCommSerialIoConfig_txBufferSize_tag 3
#define QromaCommConfig_serialIoConfig_tag       1
#define QromaCommConfig_reportingConfig_tag      2

/* Struct field encoding specification for nanopb */
#define QromaCommSerialIoConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   baudRate,          1) \
X(a, STATIC,   SINGULAR, UINT32,   rxBufferSize,      2) \
X(a, STATIC,   SINGULAR, UINT32,   txBufferSize,      3)
#define QromaCommSerialIoConfig_CALLBACK NULL
#define QromaCommSerialIoConfig_DEFAULT NULL

#define QromaCommReportingConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    logLevel,          1) \
X(a, STATIC,   SINGULAR, UINT32,   heartbeatIntervalInMs,   2)
#define QromaCommReportingConfig_CALLBACK NULL
#define QromaCommReportingConfig_DEFAULT NULL

#define QromaCommConfig_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  serialIoConfig,    1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  reportingConfig,   2)
#define QromaCommConfig_CALLBACK NULL
#define QromaCommConfig_DEFAULT NULL
#define QromaCommConfig_serialIoConfig_MSGTYPE QromaCommSerialIoConfig
#define QromaCommConfig_reportingConfig_MSGTYPE QromaCommReportingConfig

extern const pb_msgdesc_t QromaCommSerialIoConfig_msg;
extern const pb_msgdesc_t QromaCommReportingConfig_msg;
extern const pb_msgdesc_t QromaCommConfig_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define QromaCommSerialIoConfig_fields &QromaCommSerialIoConfig_msg
#define QromaCommReportingConfig_fields &QromaCommReportingConfig_msg
#define QromaCommConfig_fields &QromaCommConfig_msg

/* Maximum encoded size of messages (where known) */
#define QromaCommConfig_size                     31
#define QromaCommReportingConfig_size            9
#define QromaCommSerialIoConfig_size             18

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
